scrape_configs:
  - job_name: 'RasukanAuthMetrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['rasukan:8080']
        labels:
          application: 'Rasukan Auth'
