package advpro.b2.rasukanauth.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

public class UserTest {

    @BeforeEach
    void setUp() {}

    @Test
    void testIdAutoGenerated() {
        User user = new User();
        String id = user.getId();
        assertNotNull(id);
    }

    @Test
    void testCreateNormalUser_success() {
        String name = "User 1";
        String email = "user1@test.com";
        String password = "user1";
        String phoneNumber = "1234567890";
        Long balance = 123456789L;
        Boolean isStaff = false;
        User user = new User(name, email, password, phoneNumber, balance, isStaff);

        assertEquals(name, user.getName());
        assertEquals(email, user.getEmail());
        assertEquals(password, user.getPassword());
        assertEquals(phoneNumber, user.getPhoneNumber());
        assertEquals(balance, user.getBalance());
        assertFalse(user.isStaff());
    }

    @Test
    void testCreateStaff_success() {
        String name = "Staff 1";
        String email = "staff1@test.com";
        String password = "staff1";
        String phoneNumber = "0123456789";
        Boolean isStaff = true;
        User staff = new User(name, email, password, phoneNumber, null, isStaff);

        assertEquals(name, staff.getName());
        assertEquals(email, staff.getEmail());
        assertEquals(password, staff.getPassword());
        assertEquals(phoneNumber, staff.getPhoneNumber());
        assertNull(staff.getBalance());
        assertTrue(staff.isStaff());
    }
}
